### ISSUE TITLE
duplicated messages and duration time

### ISSUE THREAD

**Issue by Ella77** [edwardyoon/Heimdallr#4]
1) When we first entered chat, the messages will appended to iframe chat screen twice broadcasted to everyone.  

But when you erase either redis pubsub general messaging delivery(case M(channel, x) or general receive case msg in ChatRoomActor , the first chat message will be correctly appended only once. 

2) I added join button to simulate multiple users in one session. When I added new users, messaging was appended in accordance with the number of users. But as you predict, when I opened the new web browser page for each user, it will be OK. If I want to test some in same page, I need to change some websocket environment. Also, the session is now automatically stopped for some duration time. Need to discuss for setting multi room env :)

**Comment by edwardyoon** [comment]
Good point, it seems not implemented yet. I marked as a TODO.

https://github.com/edwardyoon/Heimdallr/blob/master/src/main/scala/chat/ChatRoomActor.scala#L72

**Comment by edwardyoon** [comment]
Great job. let's close this issue.
